version: "2"
services: 
  dockerapp:
    container_name: dockerapp
    restart: always
    build: .
    image: dockerapp
    ports:
      - "3000:3000"
    links:
      - mongo
  mongo:
    container_name: mongo
    image: mongo
    volumes: 
      - 'dockerapp:/data/db'
    ports: 
      - "27017:27017"
volumes:
  dockerapp:
